# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rdtVS0BGAJGS1BPmn1OHSZ_howCgXzat

**Task 09: Data linking**
"""

#pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
from rdflib.namespace import RDF, RDFS, OWL
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

ns_1 = Namespace("http://data.three.org#")
ns_2 = Namespace("http://data.four.org#")
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

for persona1, atributo1, campo1 in g1.triples((None,RDF.type, ns_1.Person)):
  for persona2, atributo2, campo2 in g2.triples((None,RDF.type, ns_2.Person)):
    if g1.value(subject=persona1, predicate=vcard.Given, object=None) == g2.value(subject=persona2, predicate=vcard.Given, object=None) and g1.value(subject=persona1, predicate=vcard.Family, object=None) == g2.value(subject=persona2, predicate=vcard.Family, object=None):
      g3.add((persona1, OWL.sameAs, persona2))

for s,p,o in g3:
  print(s,p,o)

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""