# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rX77ID8qu2bwuczKeYn-a3j1ajyxrnAm

**Task 08: Completing missing data**
"""

#pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
from rdflib.namespace import RDF, RDFS
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

ns = Namespace("http://data.org#")
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

for s, p, o in g1.triples((None,RDF.type, ns.Person)):
    if g1.value(subject=s, predicate=vcard.Given, object=None) == None:
        reemplazar = g2.value(subject=s, predicate=vcard.Given, object=None)
        g1.add((s, vcard.Given, reemplazar))
    if g1.value(subject=s, predicate=vcard.Family, object=None) == None:
        reemplazar = g2.value(subject=s, predicate=vcard.Family, object=None)
        g1.add((s, vcard.Family, reemplazar))
    if g1.value(subject=s, predicate=vcard.EMAIL, object=None) == None:
        reemplazar = g2.value(subject=s, predicate=vcard.EMAIL, object=None)
        g1.add((s, vcard.EMAIL, reemplazar))

print("Personas con campos completados:")
query = """
PREFIX ns:<http://data.org#>
PREFIX vcard:<http://www.w3.org/2001/vcard-rdf/3.0#>
SELECT ?persona ?atributo ?campo
WHERE {
  ?persona rdf:type ns:Person.
  ?persona ?atributo ?campo.
  FILTER(?atributo IN (vcard:Given, vcard:Family, vcard:EMAIL))
}
ORDER BY ?persona ?atributo
"""
for r in g1.query(query):
  print(r.persona, r.atributo, r.campo)

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""