# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colab.
**Task 08: Completing missing data**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""
RDF   = Namespace("http://www.w3.org/1999/02/22-rdf-syntax-ns#")
RDFS  = Namespace("http://www.w3.org/2000/01/rdf-schema#")
DATA = Namespace("http://data.org#")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

personas = []
for s,p,o in g1.triples((None, RDF.type, DATA.Person)):
  print(s)
  personas.append(s)

for persona in personas:
    given  = g2.value(persona, VCARD.Given)
    family = g2.value(persona, VCARD.Family)
    email  = g2.value(persona, VCARD.EMAIL)
    if given:
      g1.add((persona, VCARD.Given,  given))
    if family:
      g1.add((persona, VCARD.Family, family))
    if email:
      g1.add((persona, VCARD.EMAIL,  email))

####Visualización de g1
for persona in personas:
  for s,p,o in g1.triples((persona, VCARD.Given, None)):
    print(s,p,o)
  for s,p,o in g1.triples((persona, VCARD.Family, None)):
    print(s,p,o)
  for s,p,o in g1.triples((persona, VCARD.EMAIL,None)):
    print(s,p,o)