# -*- coding: utf-8 -*-
"""Task09.ipynb
Automatically generated by Colab.
**Task 09: Data linking**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

OWL = Namespace("http://www.w3.org/2002/07/owl#")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
RDF   = Namespace("http://www.w3.org/1999/02/22-rdf-syntax-ns#")
RDFS  = Namespace("http://www.w3.org/2000/01/rdf-schema#")
DATA3 = Namespace("http://data.three.org#")
DATA4 = Namespace("http://data.four.org#")

individuos1=[]
for s,p,o in g1.triples((None, RDF.type, DATA3.Person)):
  print(s)
  individuos1.append(s)

individuos2=[]
for s,p,o in g2.triples((None, RDF.type, DATA4.Person)):
  print(s)
  individuos2.append(s)

for i1 in individuos1:
    nombre1 = g1.value(i1, VCARD.Given, None)
    apellido1 = g1.value(i1, VCARD.Family, None)
    if nombre1 and apellido1:
        for i2 in individuos2:
            nombre2 = g2.value(i2, VCARD.Given, None)
            apellido2 = g2.value(i2, VCARD.Family, None)
            if nombre2 and apellido2:
                if (str(nombre1) == str(nombre2)) and (str(apellido1) == str(apellido2)):
                    g3.add((i1, OWL.sameAs, i2))

####Visualización de g3
for s,p,o in g3.triples((None, None, None)):
  print(s,p,o)