# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/davidgarciiapoli/Curso2025-2026-DataScience/blob/master/Assignment4/course_materials/notebooks/Task06.ipynb

**Task 06: Modifying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()

"""Create a new class named Researcher"""

ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

from rdflib import Graph, Namespace

# Crear el grafo
g = Graph()

# Crear los namespaces
ontology = Namespace("http://example.org/ontology/")
person = Namespace("http://example.org/person/")

# Asociar los prefijos al grafo
g.bind("ontology", ontology)
g.bind("person", person)

"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**

"""

g = Graph()
person = Namespace("http://oeg.fi.upm.es/def/people#")


g.bind("person", person)
for cls in ["Person", "Professor", "FullProfessor", "AssociateProfessor", "InterimAssociateProfessor"]:
    g.add((person[cls], RDF.type, RDFS.Class))

hierarchy = {
    "Professor": "Person",
    "FullProfessor": "Professor",
    "AssociateProfessor": "Professor",
    "InterimAssociateProfessor": "AssociateProfessor"
}
for subclass, superclass in hierarchy.items():
    g.add((person[subclass], RDFS.subClassOf, person[superclass]))


labels = [
    ("Person", "Person"),
    ("Professor", "Professor"),
    ("FullProfessor", "FullProfessor"),
    ("AssociateProfessor", "AssociateProfessor"),
    ("InterimAssociateProfessor", "InterimAssociateProfessor")
]
for cls, lbl in labels:
    g.add((person[cls], RDFS.label, Literal(lbl, datatype=XSD.string)))


for s, p, o in g:
    print(s, p, o)

# Validation. Do not remove
r.validate_task_06_01(g)

"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate. If a property has no range, make it a literal (string)**"""

g.add((person.hasHomePage, RDF.type, RDF.Property))
g.add((person.hasName, RDF.type, RDF.Property))
g.add((person.hasColleague, RDF.type, RDF.Property))

g.add((person.hasHomePage, RDFS.label, Literal("hasHomePage", datatype=XSD.string)))
g.add((person.hasName, RDFS.label, Literal("hasName", datatype=XSD.string)))
g.add((person.hasColleague, RDFS.label, Literal("hasColleague", datatype=XSD.string)))

g.add((person.hasHomePage, RDFS.domain, person.FullProfessor))
g.add((person.hasName, RDFS.domain, person.Person))
g.add((person.hasColleague, RDFS.domain, person.Person))

g.add((person.hasHomePage, RDFS.range, RDFS.Literal))
g.add((person.hasName, RDFS.range, RDFS.Literal))
g.add((person.hasColleague, RDFS.range, person.Person))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_02(g)

"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

data = Namespace("http://oeg.fi.upm.es/resource/person/")


g.add((data.Raul, RDF.type, person.InterimAssociateProfessor))
g.add((data.Raul, RDFS.label, Literal("Raul", datatype=XSD.string)))

g.add((data.Asun, RDF.type, person.FullProfessor))
g.add((data.Asun, RDFS.label, Literal("Asun", datatype=XSD.string)))
g.add((data.Asun, person.hasHomePage, Literal("http://www.oeg-upm.net/")))

g.add((data.Oscar, RDF.type, person.AssociateProfessor))
g.add((data.Oscar, RDFS.label, Literal("Oscar", datatype=XSD.string)))
g.add((data.Oscar, person.hasName, Literal("Óscar Corcho García")))


g.add((data.Asun, person.hasColleague, data.Raul))
g.add((data.Oscar, person.hasColleague, data.Asun))


for s, p, o in g:
  print(s, p, o)

r.validate_task_06_03(g)

"""**TASK 6.4: Add to the individual person:Oscar the email address, given and family names. Use the properties already included in example 4 to describe Jane and John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). Do not import the namespaces, add them manually**

"""

# TO DO
# Visualize the results

foaf = Namespace("http://xmlns.com/foaf/0.1/")
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")

g.namespace_manager.bind('foaf', foaf)
g.namespace_manager.bind('vcard', vcard)

g.add((data.Oscar, vcard.Given, Literal("Oscar", datatype=XSD.string)))
g.add((data.Oscar, vcard.Family, Literal("Corcho García", datatype=XSD.string)))
g.add((data.Oscar, foaf.email, Literal("ocorcho@fi.upm.es", datatype=XSD.string)))


for s, p, o in g:
  print(s, p, o)

# Validation. Do not remove
r.validate_task_06_04(g)
r.save_report("_Task_06")